# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestCatalog',
        ),
    ]
