# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0017_Adding_indeces_for_location_and_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptieragency',
            name='cgac_code',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Top-Tier Agency Code'),
        ),
    ]
