# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_Adding_test_column_for_legal_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='test_unique_id',
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='recipient_unique_id',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='DUNS Number'),
        ),
    ]
